"""empty message

Revision ID: 3e0d66d759fe
Revises: b20e14770a4e
Create Date: 2024-12-14 15:26:05.591312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0d66d759fe'
down_revision = 'b20e14770a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'Default Name'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'Default Name'::character varying"))

    # ### end Alembic commands ###
